# frpc.toml - frp client configuration (外部frpsサーバー接続)

# サーバー設定（外部frpsサーバー）
serverAddr = "frps.shiron.dev"
serverPort = 7000

# 認証設定
auth.method = "token"
auth.token = "jenkins_frp_secret_token"

# ログ設定
log.level = "info"
log.maxDays = 7

# Jenkins HTTP プロキシ設定
[[proxies]]
name = "jenkins-http"
type = "http"
localIP = "jenkins"
localPort = 8080
customDomains = ["jenkins.shiron.dev"]

[proxies.healthCheck]
type = "http"
path = "/login"
intervalSeconds = 10

# Gitea HTTP プロキシ設定
[[proxies]]
name = "gitea-http"
type = "http"
localIP = "gitea"
localPort = 3000
customDomains = ["gitea.shiron.dev"]

[proxies.healthCheck]
type = "http"
path = "/"
intervalSeconds = 10

# Jenkins TCP プロキシ設定（エージェント接続用）
[[proxies]]
name = "jenkins-tcp"
type = "tcp"
localIP = "jenkins"
localPort = 50000
remotePort = 50000

# Gitea SSH プロキシ設定
[[proxies]]
name = "gitea-ssh"
type = "tcp"
localIP = "gitea"
localPort = 22
remotePort = 2222
