[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[logger]
level = "warning"

[client]
showErrorDetails = false
