- name: Restart compose
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail
      chmod +x {{ frpclient_dir }}/docker_pre_build.sh
      {{ frpclient_dir }}/docker_pre_build.sh > {{ frpclient_dir }}/docker_pre_build.log 2>&1
      sudo docker compose down || :
      sudo docker compose up -d --build
    chdir: "{{ frpclient_dir }}"
  changed_when: true
  listen: Restart compose
