# compose.yaml

services:
  # Jenkinsサービス (変更なし)
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    depends_on:
      - git-server

  # Gitサーバーサービス
  git-server:
    build: ./git-server
    container_name: git-server
    ports:
      - "8081:80"
    volumes:
      - ./git-data:/git
    environment:
      # --- 修正点: PUID/PGIDの定義を元に戻す ---
      - GIT_USER_1=poc_user
      - GIT_PASS_1=poc_password
      - PUID=1000
      - PGID=1000
    networks:
      - ci-network

networks:
  ci-network:
