# compose.yaml (bind mount対応版)

services:
  jenkins:
    image: jenkins
    volumes:
      # --- ここからが変更点 ---
      # 名前付きボリュームからホストのディレクトリへのマウントに変更
      # - ./jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/usr/share/jenkins/ref/casc.yaml
      # --- ここまでが変更点 ---
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    # --- ここからが追記 ---
    # コンテナの実行ユーザーをホストのユーザーに合わせ、権限問題を回避する
    user: "${UID}:${GID}"
    # --- ここまでが追記 ---
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml
    env_file:
      - .env
    depends_on:
      - gitea

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      # - ./gitea-data:/data
      - gitea-data:/data
      - ./gitea/app.ini:/data/gitea/conf/app.ini
    networks:
      - ci-network

  # --- frpクライアント設定（squid経由で外部frpsサーバーに接続）---
  frpc:
    image: snowdreamtech/frpc:latest
    container_name: frpc
    volumes:
      - ./frp/frpc.toml:/etc/frp/frpc.toml
    networks:
      - ci-network
    depends_on:
      - jenkins
      - gitea
      # - squid
    restart: unless-stopped

  # squid:
  #   image: squid
  #   container_name: squid
  #   volumes:
  #     - ./squid/squid.conf:/etc/squid/squid.conf
  #   networks:
  #     - ci-network

networks:
  ci-network:

volumes:
  jenkins_home:
  gitea-data:
