# compose.yaml (bind mount対応版)

services:
  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # --- ここからが変更点 ---
      # 名前付きボリュームからホストのディレクトリへのマウントに変更
      - ./jenkins_home:/var/jenkins_home
      # --- ここまでが変更点 ---
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    # --- ここからが追記 ---
    # コンテナの実行ユーザーをホストのユーザーに合わせ、権限問題を回避する
    user: "${UID}:${GID}"
    # --- ここまでが追記 ---
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    env_file:
      - .env
    depends_on:
      - gitea

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea-data:/data
      - ./gitea/app.ini:/data/gitea/conf/app.ini
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - ci-network

# --- ここからが変更点 ---
# jenkins_home の定義を削除
# --- ここまでが変更点 ---

networks:
  ci-network:
