services:
  asr-api:
    image: asr-app
    ports:
      - "58080:8000"  # FastAPI
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./app:/app/app
      - ./static:/app/static
      - /home/students/r03i/r03i18/temp/datasets:/app/datasets
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - MALLOC_TRIM_THRESHOLD_=131072
      - MALLOC_MMAP_THRESHOLD_=131072
      - MALLOC_MMAP_MAX_=65536
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["python", "-m", "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  asr-streamlit:
    image: asr-app
    ports:
      - "58081:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./app:/app/app
      - ./static:/app/static
      - /home/students/r03i/r03i18/temp/datasets:/app/datasets
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - MALLOC_TRIM_THRESHOLD_=131072
      - MALLOC_MMAP_THRESHOLD_=131072
      - MALLOC_MMAP_MAX_=65536
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      - STREAMLIT_SERVER_MAX_MESSAGE_SIZE=200
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_GLOBAL_DEVELOPMENT_MODE=false
      - STREAMLIT_RUNNER_MAGIC_ENABLED=false
      - PYARROW_IGNORE_IMPORT_ERROR=1
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["./start_streamlit_safe.sh"]
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

