services:
  asr-app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "8000:8000"  # FastAPI
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./app:/app/app
      - ./static:/app/static
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    stdin_open: true
    tty: true

