services:
  asr-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "58081:8000"
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      # GPU設定は docker-compose.gpu.yml で上書き

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "58080:8501"
    environment:
      - BACKEND_HOST=asr-api
      - BACKEND_PORT=8000
      - NO_PROXY=asr-api,localhost,127.0.0.1
    depends_on:
      - asr-api

volumes:
  data:
    driver: local
  checkpoints:
    driver: local
