services:
  asr-app:
    image: asr-app
    ports:
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    stdin_open: true
    tty: true

