services:
  asr-app:
    image: asr-app # 絶対に修正しないでください。ホストサーバーの環境が特殊なため、このimage以外では動きません
    ports:
      - "58081:8501"  # Streamlit
      - "58080:8000"  # FastAPI
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./app:/app/app
      - ./static:/app/static
      - /home/students/r03i/r03i18/temp/datasets:/app/datasets
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    stdin_open: true
    tty: true

