# jenkins/casc.yaml
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "${GITEA_CREDENTIALS_ID}"
              username: "${GITEA_USER}"
              password: "${GITEA_PASS}"
              description: "Gitea credentials for JCasC"

# Script Security設定
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

# Job DSL設定
jobs:
  - script: >
      job('my-project-seed-job') {
        description('This seed job is created by JCasC. It reads DSL scripts from Git.')

        scm {
          git {
            remote {
              url('https://github.com/kizuna-org/asr.git')
            }
            branch('feat/poc')
          }
        }

        triggers {
          scm('H/5 * * * *')
          cron('H 2 * * *')
        }

        steps {
          jobDsl {
            targets('poc/jenkins/poc_job.groovy')
            removedJobAction('DELETE')
            removedViewAction('DELETE')
          }
        }
      }
