# jenkins/casc.yaml
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "${GITEA_CREDENTIALS_ID}"
              username: "${GITEA_USER}"
              password: "${GITEA_PASS}"
              description: "Gitea credentials for JCasC"

# Job DSL設定
jobs:
  - script: |
      multibranchPipelineJob('asr-poc') {
          displayName('asr-poc')
          description('Multibranch pipeline job for ASR POC project')

          // ジョブを有効にする
          disabled(false)

          // Branch Sources設定
          branchSources {
              git {
                  id('asr-poc-git-source')
                  // Giteaリポジトリの設定
                  remote('http://gitea:3000/poc_user/my-poc-repo.git')
                  credentialsId('poc_user')

                  // Behaviours設定
                  traits {
                      gitBranchDiscovery() // Discover branches
                  }
              }
          }

          // Build Configuration設定
          factory {
              workflowBranchProjectFactory {
                  scriptPath('Jenkinsfile') // Jenkinsfileのパス
              }
          }

          // 不要アイテムの扱い
          orphanedItemStrategy {
              discardOldItems {
                  // 古いアイテムを削除する設定
              }
          }
      }
