# kics-scan disable=d6355c88-1e8d-49e9-b2f2-f8a1ca12c75b,1c1325ff-831d-43a1-973e-839ae57dfcc0,698ed579-b239-4f8f-a388-baa4bcb13ef8
# hog
services:
  jenkins:
    image: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/usr/share/jenkins/ref/casc.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    user: "3318:513"
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml
    # env_file:
    #   - .env
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: always

  # samba:
  #   image: ghcr.io/dockur/samba:4.21.6@sha256:3b7ffd8f614deb8e93158a32709a7aea468ee30b7687b162bb2143ed04ac8340
  #   container_name: samba
  #   volumes:
  #     - ./samba:/storage
  #   networks:
  #     - ci-network
  #   environment:
  #     NAME: $SAMBA_NAME
  #     USER: $SAMBA_USER
  #     PASS: $SAMBA_PASS
  #   restart: always

  fclient:
    image: fclient
    container_name: fclient
    volumes:
      - ./fclient/fclient.toml:/etc/fclient.toml
    networks:
      - ci-network
    depends_on:
      - jenkins
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges:true

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    networks:
      - ci-network
    depends_on:
      - jenkins
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./blackbox/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  portainer:
    image: portainer/portainer-ce:2.27.0-rc2@sha256:00a51f306e154c0e1849d17d45bb4b2b947a2af28deb1e031db0adc076f97d26
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always

networks:
  ci-network:
