# frp-server/compose.yaml - frpサーバー + Cloudflare Tunnel設定

services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    volumes:
      - ./frps.toml:/etc/frp/frps.toml
      - ./logs:/var/log/frp
    restart: unless-stopped
    networks:
      - frp-network
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - frp-network
    depends_on:
      - frps

networks:
  frp-network:
