# frp-server/compose.yaml - frpサーバー専用設定（Cloudflare Dashboard管理）

services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    volumes:
      - ./frps.toml:/etc/frp/frps.toml
      - ./logs:/var/log/frp
    restart: unless-stopped
    networks:
      - frp-network

networks:
  frp-network:
