# frps.toml - frp server configuration

bindPort = 7000
# HTTP/HTTPSプロキシの設定
vhostHTTPPort = 80
vhostHTTPSPort = 443

# Webダッシュボード設定
webServer.addr = "0.0.0.0"
webServer.port = 8000
webServer.user = "admin"
webServer.password = "frp_admin_password"

# 認証設定
auth.method = "token"
auth.token = "jenkins_frp_secret_token"

# ログ設定
log.level = "info"
log.maxDays = 7

# サブドメイン設定
subDomainHost = "shiron.dev"
